name: Build and Push Docker Image to Azure Container Registry

on:
  push:
    branches:
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Azure Container Registry
        uses: docker/login-action@v1
        with:
          registry: TWMVnetPOC.azurecr.io
          username: TWMVnetPOC
          password: 8yzV28WR+6top3SvrxmetkNLTQ5A5BcuI9lp1kGhJO+ACRAF2aIh

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: TWMVnetPOC.azurecr.io/vnetsql:latest